POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "5 Big Web Design Predictions for 2022",
    "author": "Ben Moss",
    "url": "https://www.webdesignerdepot.com/2022/01/5-big-web-design-predictions-for-2022/",
    "likes": 0
}